### PR TITLE
Update PHPStan

### PR DESCRIPTION
**Pull request by dktapps**

### CODE REVIEW

**Comment by JaxkDev** [comment]
iirc the default phpstan config will need updating too

**Comment by dktapps** [comment]
why?

**Comment by dktapps** [comment]
phpstan.neon looks fine, minus the 7.3 minimum (should be 8.0 now).

**Comment by JaxkDev** [comment]
Hmm odd, kept seeing the deprecated bootstrap option pop up guess someone else was using it.
Checked and its already been done 505861d4845ae447cfc70987d44ff39f0092c82d

Yeah idk why you wanted 7.3 specifically too long ago for me to remember anything at all

**Comment by dktapps** [comment]
At the time 7.3 was the min version for PM to run on.

**Pull request merged**
